#version 460
layout(local_size_x = 64) in;


layout(push_constant) uniform constants {
  uint size;
} params;


layout(std430, binding = 0) buffer A {
  float a[];
};
layout(std430, binding = 1) readonly buffer B {
  float b[]; // min
};
layout(std430, binding = 2) readonly buffer C {
  float c[]; // max
};


void main(){
  uint i = gl_GlobalInvocationID.x;
  if(i >= params.size){ return; }

  a[i] = clamp(a[i], b[i], c[i]);
}
