#version 460
#extension GL_KHR_shader_subgroup_arithmetic: enable

layout(local_size_x = 64) in;


layout(push_constant) uniform constants {
  uint size;
} params;


layout(std430, binding = 0) readonly buffer A {
  float a[];
};
layout(std430, binding = 1) writeonly buffer B {
  float b[];
};


void main(){
  uint i = gl_GlobalInvocationID.x;
  if(i >= params.size){ return; }

  float partial_max = subgroupMax(a[i]);

  if(subgroupElect()){
    b[gl_SubgroupID] = partial_max;
  }
}
