#version 460
layout(local_size_x = 64) in;


layout(push_constant) uniform constants {
  uint size;
} params;


layout(std430, binding = 0) readonly buffer X {
  float x[];
};
layout(std430, binding = 1) readonly buffer Y {
  float y[];
};
layout(std430, binding = 2) writeonly buffer Loss {
  float L[];
};


void main(){
  uint i = gl_GlobalInvocationID.x;
  if(i >= params.size){ return; }

  L[i] = - y[i] * log(x[i] + 1e-8);
}
