#version 460
layout(local_size_x = 64) in;


layout(push_constant) uniform constants {
  uint size;
  uint low;
  uint high;
} params;


layout(std430, binding = 0) readonly buffer A {
  float a[]; // [0, 1)
};
layout(std430, binding = 1) writeonly buffer B {
  uint b[]; // [low, high]
};


void main(){
  uint i = gl_GlobalInvocationID.x;
  if(i >= params.size){ return; }

  const uint range = params.high - params.low + 1;

  b[i] = params.low + uint(range * a[i]);
}
