#version 460
layout(local_size_x = 64) in;


layout(push_constant) uniform constants {
  uint size;
} params;


layout(std430, binding = 0) readonly buffer A {
  float a[];
};
layout(std430, binding = 1) readonly buffer B {
  float b[];
};
layout(std430, binding = 2) buffer C {
  float c[];
};


void main(){
  uint i = gl_GlobalInvocationID.x;
  if(i >= params.size){ return; }

  c[i] = a[i] - b[i];
}
